# Generated by Django 4.2.5 on 2023-12-21 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddiesTravel', '0002_tourrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourVlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlog', models.FileField(upload_to='tour_vlogs')),
                ('description', models.TextField()),
                ('rating', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_vlogs', to='buddiesTravel.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_vlogs', to='buddiesTravel.user')),
            ],
        ),
    ]
